name: hangeureut
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  firebase_analytics: ^9.1.5
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  cupertino_icons: ^1.0.2
  kakao_flutter_sdk: ^1.2.1
  provider: ^6.0.2
  validators: ^3.0.0
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1
  cloud_firestore: ^3.1.14
  equatable: ^2.0.3
  material_design_icons_flutter: 5.0.6595
  image_picker: ^0.8.5+3
  cloud_functions: ^3.2.17
  persistent_bottom_nav_bar: ^4.0.2
  curved_navigation_bar: ^1.0.3
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icons/
    - images/icons/onboarding_icon/
    - images/filters/
    - images/filters/alcohol/
    - images/filters/coffee/
    - images/filters/meal/
    - images/dummies/

  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSans/GmarketSansTTFBold.ttf
          weight: 700
        - asset: assets/fonts/GmarketSans/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/fonts/GmarketSans/GmarketSansTTFLight.ttf
          weight: 300
    - family: Cafe24
      fonts:
        - asset:  assets/fonts/Cafe24Ssurround.ttf
          weight: 500
    - family: Suit
      fonts:
          - asset: assets/fonts/SUIT-ttf/SUIT-Light.ttf
            weight: 300
          - asset: assets/fonts/SUIT-ttf/SUIT-Regular.ttf
            weight: 400
          - asset: assets/fonts/SUIT-ttf/SUIT-Medium.ttf
            weight: 500

          - asset: assets/fonts/SUIT-ttf/SUIT-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/SUIT-ttf/SUIT-Bold.ttf
            weight: 700
          - asset: assets/fonts/SUIT-ttf/SUIT-ExtraBold.ttf
            weight: 800

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the fonts family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the fonts. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
