const popularRes = [
  {
    "resId": 1,
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": 4.5,
    "category1": 0,
    "tag1": 5,
    "tag2": 4,
    "detail": "돈까스 맛집입니다",
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "resId": 1,
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": 4.5,
    "category1": 0,
    "tag1": 5,
    "tag2": 4,
    "detail": "돈까스 맛집입니다",
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "resId": 1,
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": 4.5,
    "category1": 0,
    "tag1": 5,
    "tag2": 4,
    "detail": "돈까스 맛집입니다",
    "imgUrl": "images/restaurants/1.jpg",
  },
];

const nearRes = [
  {
    "resId": 2,
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": 4.5,
    "tag1": 2,
    "tag2": null,
    "detail": "라본느 맛있어요",
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "resId": 2,
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": 4.5,
    "tag1": 2,
    "tag2": null,
    "detail": "라본느 맛있어요",
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "resId": 2,
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": 4.5,
    "tag1": 2,
    "tag2": null,
    "detail": "라본느 맛있어요",
    "imgUrl": "images/restaurants/2.jpg",
  },
];
