const mainOutputList0 = [
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "리피토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "1",
    "kakaoId": "27495281",
    "name": "돈천동식당",
    "score": "4.5",
    "tag1": "기름칠",
    "tag2": "매콤한",
    "distance": 300,
    "imgUrl": "images/restaurants/1.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "기름칠",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
];

const mainOutputList2 = [
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "score": "4.5",
    "name": "라본느타르트",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
  {
    "id": "2",
    "kakaoId": "7850862",
    "name": "라본느타르트",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": null,
    "distance": 300,
    "imgUrl": "images/restaurants/2.jpg",
  },
  {
    "id": "4",
    "kakaoId": "1948873687",
    "name": "라플로레종",
    "score": "4.5",
    "tag1": "디저트",
    "tag2": "분위기",
    "distance": 300,
    "imgUrl": "images/restaurants/4.jpg",
  },
];

const mainOutputList1 = [
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
  {
    "id": "3",
    "kakaoId": null,
    "name": "라파토리아아",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "안주",
    "distance": 300,
    "imgUrl": "images/restaurants/3.jpg",
  },
  {
    "id": "5",
    "kakaoId": "1614398403",
    "name": "하우스라운",
    "score": "4.5",
    "tag1": "분위기",
    "tag2": "저렴한",
    "distance": 300,
    "imgUrl": "images/restaurants/5.jpg",
  },
];
