//수정사항        back     front
//1. tag ->    number    string
//2. score -> number    string

const mainOutput = {
  0: [
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "리피토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG",
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG",
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG",
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG",
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG",
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG"
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG"
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG"
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG"
    },
    {
      "resId": 1,
      "kakaoId": "27495281",
      "name": "돈천동식당",
      "score": 4.5,
      "tag1": 5,
      "tag2": 4,
      "distance": 300,
      "imgUrl": "images/restaurants/1.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 5,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "SOGANG"
    }
  ],
  2: [
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "score": 4.5,
      "name": "라본느타르트",
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 2,
      "kakaoId": "7850862",
      "name": "라본느타르트",
      "score": 4.5,
      "tag1": 2,
      "tag2": null,
      "distance": 300,
      "imgUrl": "images/restaurants/2.jpg",
      "univ": "YONSEI",
    },
    {
      "resId": 4,
      "kakaoId": "1948873687",
      "name": "라플로레종",
      "score": 4.5,
      "tag1": 2,
      "tag2": 1,
      "distance": 300,
      "imgUrl": "images/restaurants/4.jpg",
      "univ": "YONSEI",
    },
  ],
  1: [
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 3,
      "kakaoId": null,
      "name": "라파토리아아",
      "score": 4.5,
      "tag1": 1,
      "tag2": 2,
      "distance": 300,
      "imgUrl": "images/restaurants/3.jpg",
      "univ": "EWHA"
    },
    {
      "resId": 5,
      "kakaoId": "1614398403",
      "name": "하우스라운",
      "score": 4.5,
      "tag1": 1,
      "tag2": 0,
      "distance": 300,
      "imgUrl": "images/restaurants/5.jpg",
      "univ": "EWHA"
    },
  ]
};
