const newsOutputFriends = [
  {
    "reviewId": 23,
    "userId": "kakao:2318981232",
    "userName": "다은",
    "date": "2022년 5월 1일",
    "resName": "리피토리아",
    "resId": "3",
    "imgUrl": "images/restaurants/3_2.jpg",
    "category": 0,
    "icon": "기름칠",
    "likes": 40,
    "liked": false,
  },
  {
    "reviewId": 23,
    "userId": "kakao:2318981232",
    "userName": "다은",
    "date": "2022년 5월 1일",
    "resName": "리피토리아",
    "resId": "3",
    "imgUrl": "images/restaurants/3_2.jpg",
    "category": 0,
    "icon": "기름칠",
    "likes": 40,
    "liked": false,
  },
  {
    "reviewId": 23,
    "userId": "kakao:2318981232",
    "userName": "다은",
    "date": "2022년 5월 1일",
    "resName": "리피토리아",
    "resId": "3",
    "imgUrl": "images/restaurants/3_2.jpg",
    "category": 0,
    "icon": "기름칠",
    "likes": 40,
    "liked": false,
  },
];

const newsOutputReco = [
  {
    "reviewId": 23,
    "userId": "kakao:2318981232",
    "userName": "다은",
    "date": "2022년 5월 1일",
    "resName": "리피토리아",
    "resId": "3",
    "imgUrl": "images/restaurants/3_2.jpg",
    "category": 0,
    "icon": "기름칠",
    "likes": 40,
    "liked": false,
  },
];
